---
# roles/kubelish/handlers/main.yml

- name: restart avahi-daemon
  systemd:
    name: avahi-daemon
    state: restarted
  become: yes

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: restart kubelish
  systemd:
    name: kubelish
    state: restarted
  become: yes