---
# System preparation tasks
- name: Upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
  tags: [packages]

- name: Install Go (latest version)
  shell: |
    GO_VERSION="1.23.4"
    GO_ARCH="{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    wget -q "https://go.dev/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz" -O /tmp/go.tar.gz
    rm -rf /usr/local/go
    tar -C /usr/local -xzf /tmp/go.tar.gz
    rm /tmp/go.tar.gz
    ln -sf /usr/local/go/bin/go /usr/local/bin/go
    ln -sf /usr/local/go/bin/gofmt /usr/local/bin/gofmt
  args:
    creates: /usr/local/go/bin/go
  tags: [tools]

- name: Install OpenTofu
  shell: |
    curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o /tmp/install-opentofu.sh
    chmod +x /tmp/install-opentofu.sh
    /tmp/install-opentofu.sh --install-method deb
    rm -f /tmp/install-opentofu.sh
  args:
    creates: /usr/bin/tofu
  tags: [tools]

- name: Install yq (YAML processor)
  shell: |
    YQ_VERSION="v4.40.5"
    YQ_BINARY="yq_linux_arm64"
    wget -q "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}" -O /usr/local/bin/yq
    chmod +x /usr/local/bin/yq
  args:
    creates: /usr/local/bin/yq
  tags: [tools]

- name: Enable and start iSCSI service
  systemd:
    name: iscsid
    enabled: yes
    state: started
  tags: [services]

- name: Set timezone
  timezone:
    name: "{{ system_timezone }}"
  tags: [system]

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  tags: [networking]

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/homelab
    - /var/log/homelab
    - "{{ registry_data_dir }}"
  tags: [directories]
