---
- name: Wait for Portainer service to be available
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: portainer-service
    namespace: "{{ k8s_namespace | default('default') }}"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300

- name: Get Portainer service details
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: portainer-service
    namespace: "{{ k8s_namespace | default('default') }}"
  register: portainer_service

- name: Set Portainer service IP
  set_fact:
    portainer_ip: "{{ portainer_service.resources[0].status.loadBalancer.ingress[0].ip | default(portainer_service.resources[0].spec.clusterIP) }}"

- name: Copy Portainer configuration script
  template:
    src: configure-portainer.sh.j2
    dest: /tmp/configure-portainer.sh
    mode: '0755'
  vars:
    portainer_url: "http://{{ portainer_ip }}:80"
    portainer_admin_password: "{{ portainer_admin_password | default('homelab123!') }}"

- name: Install required packages for Portainer configuration
  package:
    name:
      - curl
      - jq
    state: present

- name: Run Portainer configuration script
  shell: /tmp/configure-portainer.sh
  environment:
    PORTAINER_ADMIN_PASSWORD: "{{ portainer_admin_password | default('homelab123!') }}"
  register: portainer_config_result

- name: Display Portainer configuration result
  debug:
    var: portainer_config_result.stdout_lines

- name: Clean up configuration script
  file:
    path: /tmp/configure-portainer.sh
    state: absent